services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    environment:
      - "RUST_LOG=debug"
      - "DATABASE_URL=sqlite:data/race_segments.db?mode=rwc"

volumes:
  backend-data:
